### ISSUE TITLE
Relative links in feeds aren't handled correctly

### ISSUE THREAD

**Issue by TheFrenchGhosty** [maubot/rss#7]
The bot seems to be broken and is posting broken HTML when Github Wiki updates happen: ``<p>New post in nitter: Recent Wiki Updates: <a href=\"/zedeus/nitter/wiki\"></a></p>`` instead of the actual link.

![s](https://user-images.githubusercontent.com/47571719/65060502-82c02480-d967-11e9-985a-50d6e25229f1.png)

(Used for the [Nitter](https://github.com/zedeus/nitter) room)

**Comment by tulir** [comment]
Looks like there are two problems there. Relative links should now be fixed, but I can't do much about the lack of a title there. You can change the template to something else, e.g. `!rss template <id> $link was edited on the Nitter wiki` (where `<id>` can be found with `!rss subscriptions`).

**Comment by TheFrenchGhosty** [comment]
Seems to be working perfectly now, thanks for the fix!

**Comment by TheFrenchGhosty** [comment]
After some days it looks like it's still working in another room... but it's still broken in the Nitter's room

**Comment by Perflyst** [comment]
It is broken again in` #bibliogram:matrix.org`
```
"content": {
    "body": "New post in bibliogram: Recent Wiki Updates: [](/cloudrac3r/bibliogram/wiki/List-of-the-different-Instagram-embeds)",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>New post in bibliogram: Recent Wiki Updates: <a href=\"/cloudrac3r/bibliogram/wiki/List-of-the-different-Instagram-embeds\"></a></p>\n",
    "msgtype": "m.notice"
  }
```

**Comment by olivia-fl** [comment]
Looks like this was actually broken by a change in the `feedparser` dependency. I submitted a patch: https://github.com/kurtmckee/feedparser/pull/503. It's likely that there are other bugs in maubot-rss triggered by the same thing. If you don't want to wait for the feedparser patch to make it in, or have trouble patching transitive dependencies, a patch like this in maubot-rss would probably work (untested):

```diff
diff --git a/rss/bot.py b/rss/bot.py
index 74c1681..a381be4 100644
--- a/rss/bot.py
+++ b/rss/bot.py
@@ -259,6 +259,9 @@ class RSSBot(Plugin):
     ) -> tuple[Feed, list[Entry]]:
         content = await resp.read()
         headers = {"Content-Location": feed.url, **resp.headers, "Content-Encoding": "identity"}
+        # workaround for <https://github.com/kurtmckee/feedparser/pull/503>
+        headers = {k.lower(): v for k, v in headers.items()}
+
         parsed_data = feedparser.parse(io.BytesIO(content), response_headers=headers)
         if parsed_data.bozo:
             if not isinstance(parsed_data.bozo_exception, feedparser.ThingsNobodyCaresAboutButMe):
```

Also worth noting: maubot-rss supports [JSON feed](https://www.jsonfeed.org/), but I don't think it attempts to handle relative links there. I wasn't sure from reading the JSON feed spec whether relative links are intended to be supported.
